### ISSUE TITLE
serve error after installed this plugin

### ISSUE THREAD

**Issue by CrystalXuLi** [SolarLiner/vue-cli-plugin-prerender-spa#16]
**Describe the bug**
this is a blank project init by vue ui, include vue-router, after install this plugin, I got an error when serve it, I haven't change any code …

**To Reproduce**
1. vue ui
2. create project
3. choose vue-router
4. search plugin vue-cli-plugin-prerender-spa and install it
5. task -> serve

**Screenshots**
![image](https://user-images.githubusercontent.com/26788425/50631696-42a74600-0f80-11e9-938a-6dbc20b14aba.png)

**Comment by SolarLiner** [comment]
Sorry, I can't reproduce. Serving works fine - besides I tested the use-case before releasing version 1.1.0.

Which version of the plugin are you using?

**Comment by savander** [comment]
I also have problem with serving project. With a bit different error. Actually, I'm using only vue project with babel and preprocessor. It's a blank project, without plugin it serves just fine. After adding plugin, it tells me that: 

`98% after emitting PrerenderSPAPluginError: ENOENT: no such file or directory, stat '<path>\dist\app.html'`.
Also, because of installing this plugin it cause to print one more error: 
```
URIError: Failed to decode param '/%3C%=%20BASE_URL%20%%3Efavicon.ico'
at decodeURIComponent (<anonymous>)
                                  at decode_param (<path>\development\node_modules\express\lib\router\layer.js:172:12)
                                  at Layer.match (<path>\development\node_modules\express\lib\router\layer.js:123:27)
                                  at matchLayer (<path>\development\node_modules\express\lib\router\index.js:574:18)
                                  at next (<path>\development\node_modules\express\lib\router\index.js:220:15)
                                  at expressInit (<path>\development\node_modules\express\lib\middleware\init.js:40:5)
                                  at Layer.handle [as handle_request] (<path>\development\node_modules\express\lib\router\layer.js:95:5)
                                  at trim_prefix (<path>\development\node_modules\express\lib\router\index.js:317:13)
                                  at <path>\development\node_modules\express\lib\router\index.js:284:7
                                  at Function.process_params (<path>\development\node_modules\express\lib\router\index.js:335:12)
                                  at next (<path>\development\node_modules\express\lib\router\index.js:275:10)
                                  at query (<path>\development\node_modules\express\lib\middleware\query.js:45:5)
                                  at Layer.handle [as handle_request] (<path>\development\node_modules\express\lib\router\layer.js:95:5)
                                  at trim_prefix (<path>\development\node_modules\express\lib\router\index.js:317:13)
                                  at <path>\development\node_modules\express\lib\router\index.js:284:7
                                  at Function.process_params (<path>\development\node_modules\express\lib\router\index.js:335:12)
```
It's default plugin config:
```
module.exports = {
  pluginOptions: {
    prerenderSpa: {
      registry: undefined,
      renderRoutes: [
        '/'
      ],
      useRenderEvent: true,
      headless: true,
      onlyProduction: true
    }
  }
}
```

**Comment by SolarLiner** [comment]
Okay, I can reproduce - I didn't see it printing the error as the console gets cleared after the dev build completes. The thing is that the plugin shouldn't even be loaded for development builds and the development server.

I'll look into it!

**Comment by SolarLiner** [comment]
I've solved the `no such file or directory: app.html` issue which led to a blank page on development builds; however now if you use pre-rendering while in development the build never finishes.

Maybe I should just hardcode-disable it if running `serve` ...

**Comment by nikmel2803** [comment]
I have the same problem: development server does not work correctly (I see only blank page).
My code: https://github.com/codex-team/hawk.so/tree/develop/frontend
When can we expect a bug fix? ;D

**Comment by SolarLiner** [comment]
I've solved the blank page issue in the hotfix branch - but that uncovered another bug that I need to fix whith Puppeteer enabled in `serve`

**Comment by savander** [comment]
It looks, like if you set `onlyProduction: false`, you have to run `npm run build` before `serve`, so PreRender will find proper `index.html`. I think, it should find for that `index.html` in different place. I'm not sure, how `serve` works.

**Comment by SolarLiner** [comment]
That is the fix I applied in the feature branch. However it still breaks with `onlyProduction: false`, though.

I'll be releasing the fix with a notice that `onlyProduction` will be forced to `true` while the bug is fixed.

**Comment by lcat** [comment]
```js
return Object.assign(options, { onlyProduction: true }); // Force disable on development build, workaround for #16
```

@SolarLiner This code will assign onlyProduction Always `true`.

If I have test or beta env. it's not work

**Comment by SolarLiner** [comment]
Yes; this is a workaround for this very issue.
